export const DEFINIR_PRODUTOS = 'DEFINIR_PRODUTOS';
export const DEFINIR_PRODUTO_POR_ID = 'DEFINIR_PRODUTO_POR_ID';
export const DEFINIR_USUARIO_LOGADO = 'DEFINIR_USUARIO_LOGADO';
export const DESLOGAR_USUARIO = 'DESLOGAR_USUARIO';